let sudokuBoard=[],sudokuSolution=[],sudokuSelected=null,sudokuErrors=0,sudokuDifficulty='facil';
function setSudokuDiff(d,btn){sudokuDifficulty=d;document.querySelectorAll('#sudoku-screen .diff-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');initSudoku();}
function generateSudoku(){const board=Array.from({length:9},()=>Array(9).fill(0));solveSudoku(board);return board;}
function solveSudoku(board){for(let r=0;r<9;r++){for(let c=0;c<9;c++){if(board[r][c]===0){const nums=shuffle([1,2,3,4,5,6,7,8,9]);for(const n of nums){if(isSafe(board,r,c,n)){board[r][c]=n;if(solveSudoku(board))return true;board[r][c]=0;}}return false;}}}return true;}
function isSafe(board,r,c,n){for(let i=0;i<9;i++){if(board[r][i]===n)return false;if(board[i][c]===n)return false;}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let i=0;i<3;i++)for(let j=0;j<3;j++){if(board[br+i][bc+j]===n)return false;}return true;}
function initSudoku(){stopAllTimers();sudokuErrors=0;sudokuSelected=null;document.getElementById('sud-errors').textContent='0';document.getElementById('sud-time').textContent='00:00';const solution=generateSudoku();sudokuSolution=solution.map(r=>[...r]);const removals={facil:30,medio:45,dificil:55};const count=removals[sudokuDifficulty]||35;const puzzle=solution.map(r=>[...r]);let removed=0;while(removed<count){const r=Math.floor(Math.random()*9);const c=Math.floor(Math.random()*9);if(puzzle[r][c]!==0){puzzle[r][c]=0;removed++;}}sudokuBoard=puzzle.map(r=>r.map(v=>({val:v,given:v!==0,player:false,error:false})));renderSudokuGrid();renderSudokuNumpad();updateSudokuLeft();startTimer('sudoku','sud-time');}
function renderSudokuGrid(){const grid=document.getElementById('sudoku-grid');grid.innerHTML='';for(let r=0;r<9;r++){for(let c=0;c<9;c++){const cell=document.createElement('div');cell.className='sudoku-cell';if(sudokuBoard[r][c].given)cell.classList.add('given');if(sudokuBoard[r][c].player)cell.classList.add('player');if(sudokuBoard[r][c].error)cell.classList.add('error');if((r+1)%3===0&&r<8)cell.classList.add('row3');if(sudokuBoard[r][c].val)cell.textContent=sudokuBoard[r][c].val;cell.dataset.r=r;cell.dataset.c=c;cell.addEventListener('click',()=>selectSudokuCell(r,c));grid.appendChild(cell);}}highlightSudoku();}
function selectSudokuCell(r,c){if(sudokuBoard[r][c].given){sudokuSelected=null;highlightSudoku();return;}sudokuSelected={r,c};highlightSudoku();}
function highlightSudoku(){const cells=document.querySelectorAll('.sudoku-cell');cells.forEach(cell=>{cell.classList.remove('selected','highlight');const r=+cell.dataset.r,c=+cell.dataset.c;if(!sudokuSelected)return;const{r:sr,c:sc}=sudokuSelected;if(r===sr&&c===sc){cell.classList.add('selected');return;}if(r===sr||c===sc||(Math.floor(r/3)===Math.floor(sr/3)&&Math.floor(c/3)===Math.floor(sc/3))){cell.classList.add('highlight');}});}
function renderSudokuNumpad(){const pad=document.getElementById('sudoku-numpad');pad.innerHTML='';for(let i=1;i<=9;i++){const btn=document.createElement('button');btn.className='numpad-btn';btn.textContent=i;btn.addEventListener('click',()=>enterSudokuNum(i));pad.appendChild(btn);}const clr=document.createElement('button');clr.className='numpad-btn clear';clr.textContent='✕ Apagar';clr.addEventListener('click',()=>enterSudokuNum(0));pad.appendChild(clr);}
function enterSudokuNum(n){if(!sudokuSelected)return;const{r,c}=sudokuSelected;if(sudokuBoard[r][c].given)return;if(n===0){sudokuBoard[r][c].val=0;sudokuBoard[r][c].player=false;sudokuBoard[r][c].error=false;}else{sudokuBoard[r][c].val=n;sudokuBoard[r][c].player=true;if(n!==sudokuSolution[r][c]){sudokuBoard[r][c].error=true;sudokuErrors++;document.getElementById('sud-errors').textContent=sudokuErrors;}else{sudokuBoard[r][c].error=false;}}renderSudokuGrid();updateSudokuLeft();checkSudokuWin();}
function updateSudokuLeft(){let left=0;sudokuBoard.forEach(row=>row.forEach(cell=>{if(!cell.val)left++;}));document.getElementById('sud-left').textContent=left;}
function checkSudokuWin(){for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(sudokuBoard[r][c].val!==sudokuSolution[r][c])return;}stopAllTimers();const t=document.getElementById('sud-time').textContent;showMsg('🎉','Parabéns!',`Sudoku completo em ${t} com ${sudokuErrors} erro(s)!`,initSudoku);}
function sudokuHint(){for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(!sudokuBoard[r][c].val&&!sudokuBoard[r][c].given){sudokuBoard[r][c].val=sudokuSolution[r][c];sudokuBoard[r][c].player=true;sudokuBoard[r][c].error=false;renderSudokuGrid();updateSudokuLeft();checkSudokuWin();return;}}}
document.addEventListener('keydown',e=>{if(currentScreen!=='sudoku-screen'||!sudokuSelected)return;if(e.key>='1'&&e.key<='9')enterSudokuNum(+e.key);if(e.key==='Backspace'||e.key==='Delete')enterSudokuNum(0);const{r,c}=sudokuSelected;if(e.key==='ArrowUp'&&r>0)selectSudokuCell(r-1,c);if(e.key==='ArrowDown'&&r<8)selectSudokuCell(r+1,c);if(e.key==='ArrowLeft'&&c>0)selectSudokuCell(r,c-1);if(e.key==='ArrowRight'&&c<8)selectSudokuCell(r,c+1);});
